extends: airbnb-base
parserOptions:
  ecmaVersion: 2020
rules: 
  comma-dangle:
    - error
    - only-multiline
  max-len:
    - error
    - 100
    - 2
    - ignoreComments: true
      ignoreUrls: true
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  no-plusplus:
    - off